# Generated by Django 4.2.5 on 2023-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_ticket_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
    ]
