# Generated by Django 4.2.5 on 2023-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticket_app', '0004_alter_manager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='groups',
            field=models.ManyToManyField(related_name='manager_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user_permissions',
            field=models.ManyToManyField(related_name='manager_permissions', to='auth.permission'),
        ),
    ]
